#pragma once
#include <cstring>
#include <unordered_map>

namespace TmSDK
{
    class Parameter
    {
    public:
        uint16_t paramName;
        uint16_t paramValue;

        Parameter(uint8_t name, uint16_t value) : paramName(name), paramValue(value) {}
        std::vector<uint8_t> GetBytes()
        {
            std::vector<uint8_t> result;
            result.push_back(static_cast<uint8_t>(paramName & 0xFF));
            result.push_back(static_cast<uint8_t>((paramName >> 8) & 0xFF));
            result.push_back(static_cast<uint8_t>(paramValue & 0xFF));        // 하위 바이트
            result.push_back(static_cast<uint8_t>((paramValue >> 8) & 0xFF)); // 상위 바이트
            return result;
        }
    };

    /// @cond DOXYGEN_SHOULD_SKIP_THIS
    class Packet
    {
    public:
        uint32_t command;
        std::vector<uint8_t> payload;
        uint8_t checksum;
            
        Packet() : command(0), checksum(0) {}
        Packet(uint32_t cmd, const std::vector<uint8_t>& data) : command(cmd), payload(data), checksum(0) {}
            
        void IntToBytes(int value, unsigned char bytes[4]) const {
            bytes[3] = (value >> 24) & 0xFF;
            bytes[2] = (value >> 16) & 0xFF;
            bytes[1] = (value >> 8) & 0xFF;
            bytes[0] = value & 0xFF;
        }
        uint16_t ToUInt16()
        {
            uint16_t val;
            memcpy(&val, payload.data(), sizeof(val));
            return val;
        }
        uint32_t ToUInt32()
        {
            uint32_t val;
            memcpy(&val, payload.data(), sizeof(val));
            return val;
        }
    };
    /// @cond DOXYGEN_SHOULD_SKIP_THIS

    class TmProtocol
    {
    public:
        static uint32_t BuildPacket(Packet pkt, uint8_t*& pktData);
        static bool ParsePacket(std::vector<uint8_t> pktData, Packet& packet);
        
        template<typename T>
        static T ByteToStruct(const std::vector<unsigned char>& buffer) {
            if (buffer.size() < sizeof(T)) {
                throw std::runtime_error("Buffer size is smaller than the structure size.");
            }

            T obj;
            memcpy(&obj, buffer.data(), sizeof(T));
            return obj;
        }

        template<typename T>
        static std::vector<uint8_t> StructToByte(const T& obj) {
            std::vector<uint8_t> arr(sizeof(T));
            memcpy(arr.data(), &obj, sizeof(T));
            return arr;
        }
    };

    /// @cond DOXYGEN_SHOULD_SKIP_THIS
    typedef enum PKT_INTERFACE : int
    {
        ERR = -1,
        UVC = 0,
        RS485 = 1,
        RS232 = 2,
        RTSP = 3
    };

    enum class PKT_ESC : uint8_t
    {
        ESC_NUL = 0x00, // NUL : NULL
        ESC_SOH = 0x01, // SOH : Start of Header
        ESC_STX = 0x02, // STX : Start of Text
        ESC_ETX = 0x03, // ETX : End of Text
        ESC_EOT = 0x04, // EOT : End of Transmission
        ESC_ACK = 0x06,
        ESC_NACK = 0x15,
        ESC_SYN = 0x16
    };

    typedef enum PKT_INDEX : uint8_t
    {
        SOH = 0,
        STX = 1,
        CMD = 2,
        LEN = 6,
        PAYLOAD = 8
    };

    typedef enum PKT_FIELD_LENGTH : uint16_t
    {
        SOH_LEN = 1,   // Start of Header
        STX_LEN = 1,   // Start of Text
        CMD_LEN = 4,   // Command
        SIZE_LEN = 2,   // Data Size
        DATA_LEN = 512, // 64; // Data Payload (Maximum)
        CS_LEN = 1,   // Checksum
        ETX_LEN = 1    // End of Text
    };

    typedef enum PKT_CMD : uint32_t
    {
        // CMD_IMAGE_XXX : 0x0001_XXXX
        CMD_IMAGE_GET_FRAME = 0x00010000,

        // CMD_TEMP_XXX : 0x0002_XXXX
        CMD_TEMP_GET_ROI = 0x00020000,

        // CMD_CTRL_XXX : 0x0003_XXXX
        CMD_CTRL_RUN_RESET = 0x00030002,
        CMD_CTRL_SET_LED = 0x00030005,
        CMD_CTRL_SET_BUZZER = 0x00030009,

        // CMD_RS485_XXX : 0x00A0_XXXX
        CMD_RS485_SPECIFIED = 0x00A00000,
        CMD_RS485_UNSPECIFIED = 0x00A000FF,

        // CMD_CAM_XXX : 0x00CX_XXXX
        // CMD_LEP_XXX : 0x00C0_0XXX
        CMD_LEP_START = 0x00C00000,
        /* CMD_LEP_AGC_XXX : 0x00C0_01XX */
        CMD_LEP_AGC_GET_ENABLE_STATE = 0x00C00100,
        CMD_LEP_AGC_SET_ENABLE_STATE = 0x00C00101,
        CMD_LEP_AGC_GET_POLICY = 0x00C00104,
        CMD_LEP_AGC_SET_POLICY = 0x00C00105,
        CMD_LEP_AGC_GET_ROI = 0x00C00108,
        CMD_LEP_AGC_SET_ROI = 0x00C00109,
        CMD_LEP_AGC_GET_HISTOGRAM_STATISTICS = 0x00C0010C,
        CMD_LEP_AGC_GET_HEQ_DAMPING_FACTOR = 0x00C00124,
        CMD_LEP_AGC_SET_HEQ_DAMPING_FACTOR = 0x00C00125,
        CMD_LEP_AGC_GET_HEQ_CLIP_LIMIT_HIGH = 0x00C0012C,
        CMD_LEP_AGC_SET_HEQ_CLIP_LIMIT_HIGH = 0x00C0012D,
        CMD_LEP_AGC_GET_HEQ_CLIP_LIMIT_LOW = 0x00C00130,
        CMD_LEP_AGC_SET_HEQ_CLIP_LIMIT_LOW = 0x00C00131,
        CMD_LEP_AGC_GET_HEQ_EMPTY_COUNT = 0x00C0013C,
        CMD_LEP_AGC_SET_HEQ_EMPTY_COUNT = 0x00C0013D,
        CMD_LEP_AGC_GET_HEQ_SCALE_FACTOR = 0x00C00144,
        CMD_LEP_AGC_SET_HEQ_SCALE_FACTOR = 0x00C00145,
        CMD_LEP_AGC_GET_CALC_ENABLE_STATE = 0x00C00148,
        CMD_LEP_AGC_SET_CALC_ENABLE_STATE = 0x00C00149,
        CMD_LEP_AGC_GET_HEQ_LINEAR_PERCENT = 0x00C0014C,
        CMD_LEP_AGC_SET_HEQ_LINEAR_PERCENT = 0x00C0014D,
        /* CMD_LEP_SYS_XXX : 0x00C0_02XX */
        CMD_LEP_SYS_RUN_PING = 0x00C00202,
        CMD_LEP_SYS_GET_STATUS = 0x00C00204,
        CMD_LEP_SYS_GET_FLIR_SERIAL_NUMBER = 0x00C00208,
        CMD_LEP_SYS_GET_CAMERA_UPTIME = 0x00C0020C,
        CMD_LEP_SYS_GET_AUX_TEMPERATURE_KELVIN = 0x00C00210,
        CMD_LEP_SYS_GET_FPA_TEMPERATURE_KELVIN = 0x00C00214,
        CMD_LEP_SYS_GET_TELEMETRY_ENABLE_STATE = 0x00C00218,
        CMD_LEP_SYS_SET_TELEMETRY_ENABLE_STATE = 0x00C00219,
        CMD_LEP_SYS_GET_TELEMETRY_LOCATION = 0x00C0021C,
        CMD_LEP_SYS_SET_TELEMETRY_LOCATION = 0x00C0021D,
        CMD_LEP_SYS_RUN_FRAME_AVERAGE = 0x00C00222,
        CMD_LEP_SYS_GET_FRAME_TO_AVERAGE = 0x00C00224,
        CMD_LEP_SYS_SET_FRAME_TO_AVERAGE = 0x00C00225,
        CMD_LEP_SYS_GET_CUST_SERIAL_NUMBER = 0x00C00228,
        CMD_LEP_SYS_GET_SCENE_STATISTICS = 0x00C0022C,
        CMD_LEP_SYS_GET_SCENE_ROI = 0x00C00230,
        CMD_LEP_SYS_SET_SCENE_ROI = 0x00C00231,
        CMD_LEP_SYS_GET_THERMAL_SHUTDOWN_COUNT = 0x00C00234,
        CMD_LEP_SYS_GET_SHUTTER_POSITION = 0x00C00238,
        CMD_LEP_SYS_SET_SHUTTER_POSITION = 0x00C00239,
        CMD_LEP_SYS_GET_FFC_SHUTTER_MODE = 0x00C0023C,
        CMD_LEP_SYS_SET_FFC_SHUTTER_MODE = 0x00C0023D,
        CMD_LEP_SYS_RUN_FFC_NORMALIZATION = 0x00C00242,
        CMD_LEP_SYS_GET_FFC_STATUS = 0x00C00244,
        CMD_LEP_SYS_GET_GAIN_MODE = 0x00C00248,
        CMD_LEP_SYS_SET_GAIN_MODE = 0x00C00249,
        CMD_LEP_SYS_GET_FFC_STATES = 0x00C0024C,
        CMD_LEP_SYS_SET_FFC_STATES = 0x00C0024D,
        CMD_LEP_SYS_GET_GAIN_MODE_OBJ = 0x00C00250,
        CMD_LEP_SYS_SET_GAIN_MODE_OBJ = 0x00C00251,
        CMD_LEP_SYS_RUN_AVERAGE_FRAMES = 0x00C002A0,
        CMD_LEP_SYS_GET_AUX_TEMPERATURE_CELCIUS = 0x00C002B0,
        CMD_LEP_SYS_GET_FPA_TEMPERATURE_CELCIUS = 0x00C002C0,
        /* CMD_LEP_VID_XXX : 0x00C0_03XX */
        CMD_LEP_VID_GET_PCOLOR_LUT = 0x00C00304,
        CMD_LEP_VID_SET_PCOLOR_LUT = 0x00C00305,
        CMD_LEP_VID_GET_USER_LUT = 0x00C00308,
        CMD_LEP_VID_SET_USER_LUT = 0x00C00309,
        CMD_LEP_VID_GET_FOCUS_CALC_ENABLE_STATE = 0x00C0030C,
        CMD_LEP_VID_SET_FOCUS_CALC_ENABLE_STATE = 0x00C0030D,
        CMD_LEP_VID_GET_FOCUS_ROI = 0x00C00310,
        CMD_LEP_VID_SET_FOCUS_ROI = 0x00C00311,
        CMD_LEP_VID_GET_FOCUS_METRIC_THRESHOLD = 0x00C00314,
        CMD_LEP_VID_SET_FOCUS_METRIC_THRESHOLD = 0x00C00315,
        CMD_LEP_VID_GET_FOCUS_METRIC = 0x00C00318,
        CMD_LEP_VID_GET_FREEZE_ENABLE_STATE = 0x00C00324,
        CMD_LEP_VID_SET_FREEZE_ENABLE_STATE = 0x00C00325,
        CMD_LEP_VID_GET_VIDEO_OUTPUT_FORMAT = 0x00C00330,
        CMD_LEP_VID_SET_VIDEO_OUTPUT_FORMAT = 0x00C00331,
        CMD_LEP_VID_GET_LOW_GAIN_PCOLOR_LUT = 0x00C00334,
        CMD_LEP_VID_SET_LOW_GAIN_PCOLOR_LUT = 0x00C00335,
        /* CMD_LEP_OEM_XXX : 0x00C0_08XX */
        CMD_LEP_OEM_RUN_POWER_ON = 0x00C00800,
        CMD_LEP_OEM_RUN_POWER_DOWN = 0x00C00802,
        CMD_LEP_OEM_GET_FLIR_PART_NUMBER = 0x00C0081C,
        CMD_LEP_OEM_GET_SOFTWARE_VERSION = 0x00C00820,
        CMD_LEP_OEM_GET_VIDEO_OUTPUT_ENABLE = 0x00C00824,
        CMD_LEP_OEM_SET_VIDEO_OUTPUT_ENABLE = 0x00C00825,
        CMD_LEP_OEM_GET_VIDEO_OUTPUT_FORMAT = 0x00C00828,
        CMD_LEP_OEM_SET_VIDEO_OUTPUT_FORMAT = 0x00C00829,
        CMD_LEP_OEM_GET_VIDEO_OUTPUT_SOURCE = 0x00C0082C,
        CMD_LEP_OEM_SET_VIDEO_OUTPUT_SOURCE = 0x00C0082D,
        CMD_LEP_OEM_GET_CUST_PART_NUMBER = 0x00C00838,
        CMD_LEP_OEM_GET_VIDEO_OUTPUT_SOURCE_CONSTANT_VALUE = 0x00C0083C,
        CMD_LEP_OEM_SET_VIDEO_OUTPUT_SOURCE_CONSTANT_VALUE = 0x00C0083D,
        CMD_LEP_OEM_RUN_REBOOT = 0x00C00842,
        CMD_LEP_OEM_GET_FFC_NORMALIZATION_TARGET = 0x00C00844,
        CMD_LEP_OEM_SET_FFC_NORMALIZATION_TARGET = 0x00C00845,
        CMD_LEP_OEM_RUN_FFC = 0x00C00846,
        CMD_LEP_OEM_GET_CAL_STATUS = 0x00C00848,
        CMD_LEP_OEM_GET_FRAME_MEAN = 0x00C0084C,
        CMD_LEP_OEM_GET_GPIO_MODE = 0x00C00854,
        CMD_LEP_OEM_SET_GPIO_MODE = 0x00C00855,
        CMD_LEP_OEM_GET_GPIO_VSYNC_PHASE_DELAY = 0x00C00858,
        CMD_LEP_OEM_SET_GPIO_VSYNC_PHASE_DELAY = 0x00C00859,
        CMD_LEP_OEM_GET_USER_DEFAULTS_STATE = 0x00C0085C,
        CMD_LEP_OEM_RUN_USER_DEFAULTS_COPY_TO_OTP = 0x00C0085E,
        CMD_LEP_OEM_RUN_USER_DEFAULTS_RESTORE = 0x00C00862,
        CMD_LEP_OEM_GET_SHUTTER_PROFILE = 0x00C00864,
        CMD_LEP_OEM_SET_SHUTTER_PROFILE = 0x00C00865,
        CMD_LEP_OEM_GET_THERMAL_SHUTTER_ENABLE = 0x00C00868,
        CMD_LEP_OEM_SET_THERMAL_SHUTTER_ENABLE = 0x00C00869,
        CMD_LEP_OEM_GET_BAD_PIXEL_REPLACE_CONTROL = 0x00C0086C,
        CMD_LEP_OEM_SET_BAD_PIXEL_REPLACE_CONTROL = 0x00C0086D,
        CMD_LEP_OEM_GET_TEMPORAL_FILTER_CONTROL = 0x00C00870,
        CMD_LEP_OEM_SET_TEMPORAL_FILTER_CONTROL = 0x00C00871,
        CMD_LEP_OEM_GET_COLUMN_NOISE_ESTIMATE_CONTROL = 0x00C00874,
        CMD_LEP_OEM_SET_COLUMN_NOISE_ESTIMATE_CONTROL = 0x00C00875,
        CMD_LEP_OEM_GET_PIXEL_NOISE_SETTINGS = 0x00C00878,
        CMD_LEP_OEM_SET_PIXEL_NOISE_SETTINGS = 0x00C00879,
        CMD_LEP_OEM_RUN_FFC_NORMALIZATION = 0x00C008A0,
        /* CMD_LEP_RAD_XXX : 0x00C0_0EXX */
        CMD_LEP_RAD_GET_RBFO_EXTERNAL = 0x00C00E04,
        CMD_LEP_RAD_SET_RBFO_EXTERNAL = 0x00C00E05,
        CMD_LEP_RAD_GET_ENABLE_STATE = 0x00C00E10,
        CMD_LEP_RAD_SET_ENABLE_STATE = 0x00C00E11,
        CMD_LEP_RAD_GET_TSHUTTER_MODE = 0x00C00E24,
        CMD_LEP_RAD_SET_TSHUTTER_MODE = 0x00C00E25,
        CMD_LEP_RAD_GET_TSHUTTER = 0x00C00E28,
        CMD_LEP_RAD_SET_TSHUTTER = 0x00C00E29,
        CMD_LEP_RAD_RUN_FFC = 0x00C00E2E,
        CMD_LEP_RAD_GET_RUN_STATUS = 0x00C00E30,
        CMD_LEP_RAD_GET_FLUX_LINEAR_PARAMS = 0x00C00EBC,
        CMD_LEP_RAD_SET_FLUX_LINEAR_PARAMS = 0x00C00EBD,
        CMD_LEP_RAD_GET_TLINEAR_ENABLE_STATE = 0x00C00EC0,
        CMD_LEP_RAD_SET_TLINEAR_ENABLE_STATE = 0x00C00EC1,
        CMD_LEP_RAD_GET_TLINEAR_RESOLUTION = 0x00C00EC4,
        CMD_LEP_RAD_SET_TLINEAR_RESOLUTION = 0x00C00EC5,
        CMD_LEP_RAD_GET_TLINEAR_AUTO_RESOLUTION = 0x00C00EC8,
        CMD_LEP_RAD_SET_TLINEAR_AUTO_RESOLUTION = 0x00C00EC9,
        CMD_LEP_RAD_GET_SPOTMETER_ROI = 0x00C00ECC,
        CMD_LEP_RAD_SET_SPOTMETER_ROI = 0x00C00ECD,
        CMD_LEP_RAD_GET_SPOTMETER_OBJ_IN_KELVIN_X100 = 0x00C00ED0,
        CMD_LEP_RAD_GET_EXTERNAL_RBFO_LOW_GAIN = 0x00C00ED8,
        CMD_LEP_RAD_SET_EXTERNAL_RBFO_LOW_GAIN = 0x00C00ED9,
        CMD_LEP_END = 0x00C00FFF,
        // CMD_TIN_XXX : 0x00C1_0XXX
        CMD_TIN_START = 0x00C10000,
        /* CMD_TIN_S_XXX : 0x00C1_00XX */
        CMD_TIN_S_XMEM_READ = 0x00C10080,
        CMD_TIN_S_XMEM_WRITE = 0x00C10081,
        CMD_TIN_S_CCI_ADDR_SET = 0x00C10082,
        /* CMD_TIN_SPI_XXX : 0x00C1_01XX */
        CMD_TIN_SPI_READ_ID = 0x00C10181,
        CMD_TIN_SPI_READ = 0x00C10182,
        CMD_TIN_SPI_WRITE = 0x00C101C2,
        CMD_TIN_SPI_RDSR = 0x00C10186,
        CMD_TIN_SPI_WRSR = 0x00C101C6,
        CMD_TIN_SPI_ERASE_FW = 0x00C10107,
        CMD_TIN_SPI_ERASE = 0x00C10108,
        CMD_TIN_SPI_WRITE_TAG = 0x00C10109,
        CMD_TIN_SPI_GET_CRC = 0x00C1018A,
        CMD_TIN_SPI_CFG_SAVE = 0x00C1010B,
        CMD_TIN_SPI_CFG_LOAD = 0x00C1010C,
        CMD_TIN_SPI_DEFAULT_CFG_SAVE = 0x00C1010D,
        CMD_TIN_SPI_DEFAULT_CFG_RESTORE = 0x00C1010E,
        /* CMD_TIN_I2C_XXX : 0x00C1_02XX */
        /* CMD_TIN_DDR_XXX : 0x00C1_03XX */
        /* CMD_TIN_SYS_XXX : 0x00C1_05XX */
        CMD_TIN_SYS_DEV_INFO_GET = 0x00C10584,
        CMD_TIN_SYS_DEV_INFO_SET = 0x00C105C4,
        CMD_TIN_SYS_RST_TO_UPDATEFW = 0x00C10507,
        CMD_TIN_SYS_RST_TO_ROM = 0x00C10508,
        /* CMD_TIN_CAPTURE_XXX : 0x00C1_06XX */
        /* CMD_TIN_OPEN_PATH_XXX : 0x00C1_07XX */
        /* CMD_TIN_ISP_DATA_XXX : 0x00C1_08XX */
        /* CMD_TIN_ISP_PARAM_XXX : 0x00C1_09XX */
        CMD_TIN_ISP_PARAM_GET = 0x00C10981,
        CMD_TIN_ISP_PARAM_SET = 0x00C109C1,
        CMD_TIN_ISP_PARAM_PSEUD_COLOR_GET = 0x00C10984,
        CMD_TIN_ISP_PARAM_PSEUD_COLOR_SET = 0x00C109C4,
        /* CMD_TIN_Y16_MODE_XXX : 0x00C1_0AXX */
        CMD_TIN_Y16_MODE_PREVIEW_START = 0x00C10A01,
        CMD_TIN_Y16_MODE_PREVIEW_STOP = 0x00C10A02,
        /* CMD_TIN_IR_XXX : 0x00C1_0BXX */
        CMD_TIN_IR_READ_ID = 0x00C10B82,
        /* CMD_TIN_SHUTTER_XXX : 0x00C1_0CXX */
        CMD_TIN_SHUTTER_STA_SET = 0x00C10C41,
        CMD_TIN_SHUTTER_SWITCH = 0x00C10C42,
        CMD_TIN_SHUTTER_STA_GET = 0x00C10C83,
        CMD_TIN_SHUTTER_VTEMP_GET = 0x00C10C89,
        /* CMD_TIN_FW_ISP_XXX : 0x00C1_0DXX */
        CMD_TIN_FW_ISP_OOC_B_UPDATE = 0x00C10DC1,
        CMD_TIN_FW_ISP_RMCOVER_DISABLE = 0x00C10D05,
        CMD_TIN_FW_ISP_GET_CUR_TEMP_AREA = 0x00C10D8A,
        CMD_TIN_FW_ISP_GET_CUR_VTEMP = 0x00C10D8B,
        CMD_TIN_FW_ISP_JK_CAL = 0x00C10D0C,
        CMD_TIN_FW_ISP_RMCOVER_ENABLE = 0x00C10D0D,
        CMD_TIN_FW_ISP_AUTO_CAL_RMCOVER = 0x00C10D0E,
        /* CMD_TIN_FW_TPD_XXX : 0x00C1_0EXX */
        CMD_TIN_TPD_E_SET = 0x00C10E01,
        CMD_TIN_TPD_E_GET = 0x00C10E81,
        CMD_TIN_TPD_D_SET = 0x00C10E02,
        CMD_TIN_TPD_D_GET = 0x00C10E82,
        CMD_TIN_TPD_US_SET = 0x00C10E03,
        CMD_TIN_TPD_US_GET = 0x00C10E83,
        CMD_TIN_TPD_KTBT_RECAL_1_POINT = 0x00C10EC4,
        CMD_TIN_TPD_KTBT_RECAL_2_POINT = 0x00C10EC5,
        CMD_TIN_TPD_GAIN_SET = 0x00C10E06,
        /* CMD_TIN_PREVIEW_XXX : 0x00C1_0FXX */
        CMD_TIN_PREVIEW_START = 0x00C10FC1,
        CMD_TIN_PREVIEW_STOP = 0x00C10FC1,
        CMD_TIN_PREVIEW_VIDEOMODE_SET = 0x00C10E03,
        CMD_TIN_PREVIEW_VIDEOMODE_GET = 0x00C10E83,
        /* CMD_TIN_L_SPI_XXX : 0x00C1_10XX */
        CMD_TIN_L_SPI_READ_ID = 0x00C11000,
        /* CMD_TIN_L_TPD_XXX : 0x00C1_11XX */
        CMD_TIN_L_TPD_GET_MAX_TEMP = 0x00C11181,
        CMD_TIN_L_TPD_GET_MIN_TEMP = 0x00C11182,
        CMD_TIN_L_TPD_GET_MAX_MIN_TEMP_INFO = 0x00C11183,
        CMD_TIN_L_TPD_SET_MAX_MIN_TEMP_THD = 0x00C11104,
        CMD_TIN_L_TPD_GET_POINT_TEMP = 0x00C11186,
        CMD_TIN_L_TPD_SET_POINT_TEMP_THD = 0x00C11107,
        CMD_TIN_L_TPD_GET_LINE_TEMP = 0x00C11189,
        CMD_TIN_L_TPD_SET_LINE_TEMP_THD = 0x00C1110A,
        CMD_TIN_L_TPD_GET_RECT_TEMP = 0x00C1118C,
        CMD_TIN_L_TPD_SET_RECT_TEMP_THD = 0x00C1110D,
        CMD_TIN_L_TPD_SHOW_POINT_TEMP = 0x00C1110F,
        CMD_TIN_L_TPD_HIDE_POINT_TEMP = 0x00C11110,
        CMD_TIN_L_TPD_SHOW_LINE_TEMP = 0x00C11111,
        CMD_TIN_L_TPD_HIDE_LINE_TEMP = 0x00C11112,
        CMD_TIN_L_TPD_SHOW_RECT_TEMP = 0x00C11113,
        CMD_TIN_L_TPD_HIDE_RECT_TEMP = 0x00C11114,
        CMD_TIN_L_TPD_SHOW_FRAME_TEMP = 0x00C11115,
        CMD_TIN_L_TPD_HIDE_FRAME_TEMP = 0x00C11116,
        /* CMD_TIN_L_ZOOM_XXX : 0x00C1_12XX */
        CMD_TIN_L_ZOOM_CENTER_UP = 0x00C11201,
        CMD_TIN_L_ZOOM_CENTER_DOWN = 0x00C11202,
        CMD_TIN_L_ZOOM_POSITION_UP = 0x00C11203,
        CMD_TIN_L_ZOOM_POSITION_DOWN = 0x00C11204,
        /* CMD_TIN_L_DPC_XXX : 0x00C1_13XX */
        CMD_TIN_L_DPC_ADD_DP = 0x00C11301,
        CMD_TIN_L_DPC_REMOVE_DP = 0x00C11302,
        CMD_TIN_L_DPC_AUTO_CALIBRATION = 0x00C11303,
        /* CMD_TIN_L_PROP_XXX : 0x00C1_14XX */
        CMD_TIN_L_PROP_LOAD_DEFAULT_PARAM = 0x00C11401,
        CMD_TIN_L_PROP_AUTO_SHUTTER_PARAM_SET = 0x00C114C2,
        CMD_TIN_L_PROP_AUTO_SHUTTER_PARAM_GET = 0x00C11482,
        CMD_TIN_L_PROP_IMAGE_PARAM_SET = 0x00C114C3,
        CMD_TIN_L_PROP_IMAGE_PARAM_GET = 0x00C11483,
        CMD_TIN_L_PROP_OVER_EXPOSURE_SET = 0x00C114C4,
        CMD_TIN_L_PROP_OVER_EXPOSURE_GET = 0x00C11484,
        CMD_TIN_L_PROP_TPD_PARAM_SET = 0x00C114C5,
        CMD_TIN_L_PROP_TPD_PARAM_GET = 0x00C11485,
        CMD_TIN_END = 0x00C11FFF,
        // CMD_HI3217_XXX : 0x00C2_0XXX
        CMD_HI3217_START = 0x00C20000,
        CMD_HI3217_END = 0x00C20FFF,
        // CMD_CAM_HI1612_XXX : 0x00C2_1XXX
        CMD_HI1612_START = 0x00C21000,
        CMD_HI1612_END = 0x00C21FFF,
        // CMD_CAM_HI6417_XXX : 0x00C2_2XXX
        CMD_HI6417_START = 0x00C22000,
        CMD_HI6417_END = 0x00C22FFF,

        // CMD_CFG_XXX : 0x00FD_XXXX
        CMD_CFG_SET_DEFAULT = 0x00FD0002,
        CMD_CFG_READ_START = 0x00FD0006,
        CMD_CFG_READ_ING = 0x00FD0008,
        CMD_CFG_READ_END = 0x00FD000E,
        CMD_CFG_WRITE_START = 0x00FD0012,
        CMD_CFG_WRITE_ING = 0x00FD0015,
        CMD_CFG_WRITE_END = 0x00FD001A,
        CMD_CFG_SEC_SET_DEFAULT = 0x00FD0022,
        CMD_CFG_SEC_READ_START = 0x00FD0026,
        CMD_CFG_SEC_READ_ING = 0x00FD0028,
        CMD_CFG_SEC_READ_END = 0x00FD002E,
        CMD_CFG_SEC_WRITE_START = 0x00FD0032,
        CMD_CFG_SEC_WRITE_ING = 0x00FD0035,
        CMD_CFG_SEC_WRITE_END = 0x00FD003A,
        CMD_CFG_SEC_CHANGE_PW = 0x00FD0042,

        // CMD_SYS_XXX : 0x00FE_XXXX
        CMD_SYS_GET_VERSION = 0x00FE0000,
        CMD_SYS_GET_STATE = 0x00FE0004,
        CMD_SYS_GET_WHERE = 0x00FE0008,
        CMD_SYS_SET_WHERE = 0x00FE0009,
        CMD_SYS_GET_MODEL_NAME = 0x00FE000C,
        CMD_SYS_GET_PRODUCT_SN = 0x00FE0010,
        CMD_SYS_GET_UPTIME = 0x00FE0014,

        // CMD_FLASH_XXX : 0x00FF_XXXX
        CMD_FLASH_START = 0x00FF0002,
        CMD_FLASH_ING = 0x00FF0005,
        CMD_FLASH_END = 0x00FF000A,

        // CMD_XXX_XXX | 0x8000_0000
        CMD_NACK = 0x80000000
    };

    const std::unordered_map<uint32_t, uint16_t> RecvPktLen = {
        {PKT_CMD::CMD_IMAGE_GET_FRAME	,	10},
        {PKT_CMD::CMD_TEMP_GET_ROI	,	10},
        {PKT_CMD::CMD_CTRL_RUN_RESET	,	10},
        {PKT_CMD::CMD_CTRL_SET_LED	,	10},
        {PKT_CMD::CMD_CTRL_SET_BUZZER	,	10},
        {PKT_CMD::CMD_RS485_SPECIFIED	,	10},
        {PKT_CMD::CMD_RS485_UNSPECIFIED	,	10},
        {PKT_CMD::CMD_LEP_START	,	10},
        {PKT_CMD::CMD_LEP_AGC_GET_ENABLE_STATE	,	10},
        {PKT_CMD::CMD_LEP_AGC_SET_ENABLE_STATE	,	10},
        {PKT_CMD::CMD_LEP_AGC_GET_POLICY	,	10},
        {PKT_CMD::CMD_LEP_AGC_SET_POLICY	,	10},
        {PKT_CMD::CMD_LEP_AGC_GET_ROI	,	10},
        {PKT_CMD::CMD_LEP_AGC_SET_ROI	,	10},
        {PKT_CMD::CMD_LEP_AGC_GET_HISTOGRAM_STATISTICS	,	10},
        {PKT_CMD::CMD_LEP_AGC_GET_HEQ_DAMPING_FACTOR	,	10},
        {PKT_CMD::CMD_LEP_AGC_SET_HEQ_DAMPING_FACTOR	,	10},
        {PKT_CMD::CMD_LEP_AGC_GET_HEQ_CLIP_LIMIT_HIGH	,	10},
        {PKT_CMD::CMD_LEP_AGC_SET_HEQ_CLIP_LIMIT_HIGH	,	10},
        {PKT_CMD::CMD_LEP_AGC_GET_HEQ_CLIP_LIMIT_LOW	,	10},
        {PKT_CMD::CMD_LEP_AGC_SET_HEQ_CLIP_LIMIT_LOW	,	10},
        {PKT_CMD::CMD_LEP_AGC_GET_HEQ_EMPTY_COUNT	,	10},
        {PKT_CMD::CMD_LEP_AGC_SET_HEQ_EMPTY_COUNT	,	10},
        {PKT_CMD::CMD_LEP_AGC_GET_HEQ_SCALE_FACTOR	,	10},
        {PKT_CMD::CMD_LEP_AGC_SET_HEQ_SCALE_FACTOR	,	10},
        {PKT_CMD::CMD_LEP_AGC_GET_CALC_ENABLE_STATE	,	10},
        {PKT_CMD::CMD_LEP_AGC_SET_CALC_ENABLE_STATE	,	10},
        {PKT_CMD::CMD_LEP_AGC_GET_HEQ_LINEAR_PERCENT	,	10},
        {PKT_CMD::CMD_LEP_AGC_SET_HEQ_LINEAR_PERCENT	,	10},
        {PKT_CMD::CMD_LEP_SYS_RUN_PING	,	10},
        {PKT_CMD::CMD_LEP_SYS_GET_STATUS	,	10},
        {PKT_CMD::CMD_LEP_SYS_GET_FLIR_SERIAL_NUMBER	,	18},
        {PKT_CMD::CMD_LEP_SYS_GET_CAMERA_UPTIME	,	14},
        {PKT_CMD::CMD_LEP_SYS_GET_AUX_TEMPERATURE_KELVIN	,	10},
        {PKT_CMD::CMD_LEP_SYS_GET_FPA_TEMPERATURE_KELVIN	,	10},
        {PKT_CMD::CMD_LEP_SYS_GET_TELEMETRY_ENABLE_STATE	,	10},
        {PKT_CMD::CMD_LEP_SYS_SET_TELEMETRY_ENABLE_STATE	,	10},
        {PKT_CMD::CMD_LEP_SYS_GET_TELEMETRY_LOCATION	,	10},
        {PKT_CMD::CMD_LEP_SYS_SET_TELEMETRY_LOCATION	,	10},
        {PKT_CMD::CMD_LEP_SYS_RUN_FRAME_AVERAGE	,	10},
        {PKT_CMD::CMD_LEP_SYS_GET_FRAME_TO_AVERAGE	,	10},
        {PKT_CMD::CMD_LEP_SYS_SET_FRAME_TO_AVERAGE	,	10},
        {PKT_CMD::CMD_LEP_SYS_GET_CUST_SERIAL_NUMBER	,	10},
        {PKT_CMD::CMD_LEP_SYS_GET_SCENE_STATISTICS	,	10},
        {PKT_CMD::CMD_LEP_SYS_GET_SCENE_ROI	,	10},
        {PKT_CMD::CMD_LEP_SYS_SET_SCENE_ROI	,	10},
        {PKT_CMD::CMD_LEP_SYS_GET_THERMAL_SHUTDOWN_COUNT	,	10},
        {PKT_CMD::CMD_LEP_SYS_GET_SHUTTER_POSITION	,	10},
        {PKT_CMD::CMD_LEP_SYS_SET_SHUTTER_POSITION	,	10},
        {PKT_CMD::CMD_LEP_SYS_GET_FFC_SHUTTER_MODE	,	30},
        {PKT_CMD::CMD_LEP_SYS_SET_FFC_SHUTTER_MODE	,	10},
        {PKT_CMD::CMD_LEP_SYS_RUN_FFC_NORMALIZATION	,	10},
        {PKT_CMD::CMD_LEP_SYS_GET_FFC_STATUS	,	10},

        {PKT_CMD::CMD_LEP_SYS_GET_GAIN_MODE	,	14},
        {PKT_CMD::CMD_LEP_SYS_SET_GAIN_MODE	,	10},
        {PKT_CMD::CMD_LEP_SYS_GET_FFC_STATES	,	10},
        {PKT_CMD::CMD_LEP_SYS_SET_FFC_STATES	,	10},
        {PKT_CMD::CMD_LEP_SYS_GET_GAIN_MODE_OBJ	,	24},
        {PKT_CMD::CMD_LEP_SYS_SET_GAIN_MODE_OBJ	,	10},
        {PKT_CMD::CMD_LEP_SYS_RUN_AVERAGE_FRAMES	,	10},
        {PKT_CMD::CMD_LEP_SYS_GET_AUX_TEMPERATURE_CELCIUS	,	10},
        {PKT_CMD::CMD_LEP_SYS_GET_FPA_TEMPERATURE_CELCIUS	,	10},
        {PKT_CMD::CMD_LEP_VID_GET_PCOLOR_LUT	,	10},
        {PKT_CMD::CMD_LEP_VID_SET_PCOLOR_LUT	,	10},
        {PKT_CMD::CMD_LEP_VID_GET_USER_LUT	,	10},
        {PKT_CMD::CMD_LEP_VID_SET_USER_LUT	,	10},
        {PKT_CMD::CMD_LEP_VID_GET_FOCUS_CALC_ENABLE_STATE	,	10},
        {PKT_CMD::CMD_LEP_VID_SET_FOCUS_CALC_ENABLE_STATE	,	10},
        {PKT_CMD::CMD_LEP_VID_GET_FOCUS_ROI	,	10},
        {PKT_CMD::CMD_LEP_VID_SET_FOCUS_ROI	,	10},
        {PKT_CMD::CMD_LEP_VID_GET_FOCUS_METRIC_THRESHOLD	,	10},
        {PKT_CMD::CMD_LEP_VID_SET_FOCUS_METRIC_THRESHOLD	,	10},
        {PKT_CMD::CMD_LEP_VID_GET_FOCUS_METRIC	,	10},
        {PKT_CMD::CMD_LEP_VID_GET_FREEZE_ENABLE_STATE	,	10},
        {PKT_CMD::CMD_LEP_VID_SET_FREEZE_ENABLE_STATE	,	10},
        {PKT_CMD::CMD_LEP_VID_GET_VIDEO_OUTPUT_FORMAT	,	10},
        {PKT_CMD::CMD_LEP_VID_SET_VIDEO_OUTPUT_FORMAT	,	10},
        {PKT_CMD::CMD_LEP_VID_GET_LOW_GAIN_PCOLOR_LUT	,	10},
        {PKT_CMD::CMD_LEP_VID_SET_LOW_GAIN_PCOLOR_LUT	,	10},
        {PKT_CMD::CMD_LEP_OEM_RUN_POWER_ON	,	10},
        {PKT_CMD::CMD_LEP_OEM_RUN_POWER_DOWN	,	10},
        {PKT_CMD::CMD_LEP_OEM_GET_FLIR_PART_NUMBER	,	42},
        {PKT_CMD::CMD_LEP_OEM_GET_SOFTWARE_VERSION	,	10},
        {PKT_CMD::CMD_LEP_OEM_GET_VIDEO_OUTPUT_ENABLE	,	10},
        {PKT_CMD::CMD_LEP_OEM_SET_VIDEO_OUTPUT_ENABLE	,	10},
        {PKT_CMD::CMD_LEP_OEM_GET_VIDEO_OUTPUT_FORMAT	,	10},
        {PKT_CMD::CMD_LEP_OEM_SET_VIDEO_OUTPUT_FORMAT	,	10},
        {PKT_CMD::CMD_LEP_OEM_GET_VIDEO_OUTPUT_SOURCE	,	10},
        {PKT_CMD::CMD_LEP_OEM_SET_VIDEO_OUTPUT_SOURCE	,	10},
        {PKT_CMD::CMD_LEP_OEM_GET_CUST_PART_NUMBER	,	10},
        {PKT_CMD::CMD_LEP_OEM_GET_VIDEO_OUTPUT_SOURCE_CONSTANT_VALUE	,	10},
        {PKT_CMD::CMD_LEP_OEM_SET_VIDEO_OUTPUT_SOURCE_CONSTANT_VALUE	,	10},
        {PKT_CMD::CMD_LEP_OEM_RUN_REBOOT	,	10},
        {PKT_CMD::CMD_LEP_OEM_GET_FFC_NORMALIZATION_TARGET	,	10},
        {PKT_CMD::CMD_LEP_OEM_SET_FFC_NORMALIZATION_TARGET	,	10},
        {PKT_CMD::CMD_LEP_OEM_RUN_FFC	,	10},
        {PKT_CMD::CMD_LEP_OEM_GET_CAL_STATUS	,	10},
        {PKT_CMD::CMD_LEP_OEM_GET_FRAME_MEAN	,	10},
        {PKT_CMD::CMD_LEP_OEM_GET_GPIO_MODE	,	10},
        {PKT_CMD::CMD_LEP_OEM_SET_GPIO_MODE	,	10},
        {PKT_CMD::CMD_LEP_OEM_GET_GPIO_VSYNC_PHASE_DELAY	,	10},
        {PKT_CMD::CMD_LEP_OEM_SET_GPIO_VSYNC_PHASE_DELAY	,	10},
        {PKT_CMD::CMD_LEP_OEM_GET_USER_DEFAULTS_STATE	,	10},
        {PKT_CMD::CMD_LEP_OEM_RUN_USER_DEFAULTS_COPY_TO_OTP	,	10},
        {PKT_CMD::CMD_LEP_OEM_RUN_USER_DEFAULTS_RESTORE	,	10},
        {PKT_CMD::CMD_LEP_OEM_GET_SHUTTER_PROFILE	,	10},
        {PKT_CMD::CMD_LEP_OEM_SET_SHUTTER_PROFILE	,	10},
        {PKT_CMD::CMD_LEP_OEM_GET_THERMAL_SHUTTER_ENABLE	,	10},
        {PKT_CMD::CMD_LEP_OEM_SET_THERMAL_SHUTTER_ENABLE	,	10},
        {PKT_CMD::CMD_LEP_OEM_GET_BAD_PIXEL_REPLACE_CONTROL	,	10},
        {PKT_CMD::CMD_LEP_OEM_SET_BAD_PIXEL_REPLACE_CONTROL	,	10},
        {PKT_CMD::CMD_LEP_OEM_GET_TEMPORAL_FILTER_CONTROL	,	10},
        {PKT_CMD::CMD_LEP_OEM_SET_TEMPORAL_FILTER_CONTROL	,	10},
        {PKT_CMD::CMD_LEP_OEM_GET_COLUMN_NOISE_ESTIMATE_CONTROL	,	10},
        {PKT_CMD::CMD_LEP_OEM_SET_COLUMN_NOISE_ESTIMATE_CONTROL	,	10},
        {PKT_CMD::CMD_LEP_OEM_GET_PIXEL_NOISE_SETTINGS	,	10},
        {PKT_CMD::CMD_LEP_OEM_SET_PIXEL_NOISE_SETTINGS	,	10},
        {PKT_CMD::CMD_LEP_OEM_RUN_FFC_NORMALIZATION	,	10},
        {PKT_CMD::CMD_LEP_RAD_GET_RBFO_EXTERNAL	,	10},
        {PKT_CMD::CMD_LEP_RAD_SET_RBFO_EXTERNAL	,	10},
        {PKT_CMD::CMD_LEP_RAD_GET_ENABLE_STATE	,	10},
        {PKT_CMD::CMD_LEP_RAD_SET_ENABLE_STATE	,	10},
        {PKT_CMD::CMD_LEP_RAD_GET_TSHUTTER_MODE	,	10},
        {PKT_CMD::CMD_LEP_RAD_SET_TSHUTTER_MODE	,	10},
        {PKT_CMD::CMD_LEP_RAD_GET_TSHUTTER	,	10},
        {PKT_CMD::CMD_LEP_RAD_SET_TSHUTTER	,	10},
        {PKT_CMD::CMD_LEP_RAD_RUN_FFC	,	10},
        {PKT_CMD::CMD_LEP_RAD_GET_RUN_STATUS	,	10},
        {PKT_CMD::CMD_LEP_RAD_GET_FLUX_LINEAR_PARAMS	,	26},
        {PKT_CMD::CMD_LEP_RAD_SET_FLUX_LINEAR_PARAMS	,	10},
        {PKT_CMD::CMD_LEP_RAD_GET_TLINEAR_ENABLE_STATE	,	10},
        {PKT_CMD::CMD_LEP_RAD_SET_TLINEAR_ENABLE_STATE	,	10},
        {PKT_CMD::CMD_LEP_RAD_GET_TLINEAR_RESOLUTION	,	10},
        {PKT_CMD::CMD_LEP_RAD_SET_TLINEAR_RESOLUTION	,	10},
        {PKT_CMD::CMD_LEP_RAD_GET_TLINEAR_AUTO_RESOLUTION	,	10},
        {PKT_CMD::CMD_LEP_RAD_SET_TLINEAR_AUTO_RESOLUTION	,	10},
        {PKT_CMD::CMD_LEP_RAD_GET_SPOTMETER_ROI	,	10},
        {PKT_CMD::CMD_LEP_RAD_SET_SPOTMETER_ROI	,	10},
        {PKT_CMD::CMD_LEP_RAD_GET_SPOTMETER_OBJ_IN_KELVIN_X100	,	10},
        {PKT_CMD::CMD_LEP_RAD_GET_EXTERNAL_RBFO_LOW_GAIN	,	10},
        {PKT_CMD::CMD_LEP_RAD_SET_EXTERNAL_RBFO_LOW_GAIN	,	10},
        {PKT_CMD::CMD_LEP_END	,	10},
        {PKT_CMD::CMD_TIN_START	,	10},
        {PKT_CMD::CMD_TIN_S_XMEM_READ	,	10},
        {PKT_CMD::CMD_TIN_S_XMEM_WRITE	,	10},
        {PKT_CMD::CMD_TIN_S_CCI_ADDR_SET	,	10},
        {PKT_CMD::CMD_TIN_SPI_READ_ID	,	10},
        {PKT_CMD::CMD_TIN_SPI_READ	,	10},
        {PKT_CMD::CMD_TIN_SPI_WRITE	,	10},
        {PKT_CMD::CMD_TIN_SPI_RDSR	,	10},
        {PKT_CMD::CMD_TIN_SPI_WRSR	,	10},
        {PKT_CMD::CMD_TIN_SPI_ERASE_FW	,	10},
        {PKT_CMD::CMD_TIN_SPI_ERASE	,	10},
        {PKT_CMD::CMD_TIN_SPI_WRITE_TAG	,	10},
        {PKT_CMD::CMD_TIN_SPI_GET_CRC	,	10},
        {PKT_CMD::CMD_TIN_SPI_CFG_SAVE	,	10},
        {PKT_CMD::CMD_TIN_SPI_CFG_LOAD	,	10},
        {PKT_CMD::CMD_TIN_SPI_DEFAULT_CFG_SAVE	,	10},
        {PKT_CMD::CMD_TIN_SPI_DEFAULT_CFG_RESTORE	,	10},
        {PKT_CMD::CMD_TIN_SYS_DEV_INFO_GET	,	74},
        {PKT_CMD::CMD_TIN_SYS_DEV_INFO_SET	,	10},
        {PKT_CMD::CMD_TIN_SYS_RST_TO_UPDATEFW	,	10},
        {PKT_CMD::CMD_TIN_SYS_RST_TO_ROM	,	10},
        {PKT_CMD::CMD_TIN_ISP_PARAM_GET	,	10},
        {PKT_CMD::CMD_TIN_ISP_PARAM_SET	,	10},
        {PKT_CMD::CMD_TIN_ISP_PARAM_PSEUD_COLOR_GET	,	10},
        {PKT_CMD::CMD_TIN_ISP_PARAM_PSEUD_COLOR_SET	,	10},
        {PKT_CMD::CMD_TIN_Y16_MODE_PREVIEW_START	,	10},
        {PKT_CMD::CMD_TIN_Y16_MODE_PREVIEW_STOP	,	10},
        {PKT_CMD::CMD_TIN_IR_READ_ID	,	10},
        {PKT_CMD::CMD_TIN_SHUTTER_STA_SET	,	10},
        {PKT_CMD::CMD_TIN_SHUTTER_SWITCH	,	10},
        {PKT_CMD::CMD_TIN_SHUTTER_STA_GET	,	10},
        {PKT_CMD::CMD_TIN_SHUTTER_VTEMP_GET	,	10},
        {PKT_CMD::CMD_TIN_FW_ISP_OOC_B_UPDATE	,	10},
        {PKT_CMD::CMD_TIN_FW_ISP_RMCOVER_DISABLE	,	10},
        {PKT_CMD::CMD_TIN_FW_ISP_GET_CUR_TEMP_AREA	,	10},
        {PKT_CMD::CMD_TIN_FW_ISP_GET_CUR_VTEMP	,	10},
        {PKT_CMD::CMD_TIN_FW_ISP_JK_CAL	,	10},
        {PKT_CMD::CMD_TIN_FW_ISP_RMCOVER_ENABLE	,	10},
        {PKT_CMD::CMD_TIN_FW_ISP_AUTO_CAL_RMCOVER	,	10},
        {PKT_CMD::CMD_TIN_TPD_E_SET	,	10},
        {PKT_CMD::CMD_TIN_TPD_E_GET	,	10},
        {PKT_CMD::CMD_TIN_TPD_D_SET	,	10},
        {PKT_CMD::CMD_TIN_TPD_D_GET	,	10},
        {PKT_CMD::CMD_TIN_TPD_US_SET	,	10},
        {PKT_CMD::CMD_TIN_TPD_US_GET	,	10},
        {PKT_CMD::CMD_TIN_TPD_KTBT_RECAL_1_POINT	,	0},
        {PKT_CMD::CMD_TIN_TPD_KTBT_RECAL_2_POINT	,	10},
        {PKT_CMD::CMD_TIN_TPD_GAIN_SET	,	10},
        {PKT_CMD::CMD_TIN_PREVIEW_START	,	10},
        {PKT_CMD::CMD_TIN_PREVIEW_STOP	,	10},
        {PKT_CMD::CMD_TIN_PREVIEW_VIDEOMODE_SET	,	10},
        {PKT_CMD::CMD_TIN_PREVIEW_VIDEOMODE_GET	,	10},
        {PKT_CMD::CMD_TIN_L_SPI_READ_ID	,	10},
        {PKT_CMD::CMD_TIN_L_TPD_GET_MAX_TEMP	,	10},
        {PKT_CMD::CMD_TIN_L_TPD_GET_MIN_TEMP	,	10},
        {PKT_CMD::CMD_TIN_L_TPD_GET_MAX_MIN_TEMP_INFO	,	10},
        {PKT_CMD::CMD_TIN_L_TPD_SET_MAX_MIN_TEMP_THD	,	10},
        {PKT_CMD::CMD_TIN_L_TPD_GET_POINT_TEMP	,	10},
        {PKT_CMD::CMD_TIN_L_TPD_SET_POINT_TEMP_THD	,	10},
        {PKT_CMD::CMD_TIN_L_TPD_GET_LINE_TEMP	,	10},
        {PKT_CMD::CMD_TIN_L_TPD_SET_LINE_TEMP_THD	,	10},
        {PKT_CMD::CMD_TIN_L_TPD_GET_RECT_TEMP	,	10},
        {PKT_CMD::CMD_TIN_L_TPD_SET_RECT_TEMP_THD	,	10},
        {PKT_CMD::CMD_TIN_L_TPD_SHOW_POINT_TEMP	,	10},
        {PKT_CMD::CMD_TIN_L_TPD_HIDE_POINT_TEMP	,	10},
        {PKT_CMD::CMD_TIN_L_TPD_SHOW_LINE_TEMP	,	10},
        {PKT_CMD::CMD_TIN_L_TPD_HIDE_LINE_TEMP	,	10},
        {PKT_CMD::CMD_TIN_L_TPD_SHOW_RECT_TEMP	,	10},
        {PKT_CMD::CMD_TIN_L_TPD_HIDE_RECT_TEMP	,	10},
        {PKT_CMD::CMD_TIN_L_TPD_SHOW_FRAME_TEMP	,	10},
        {PKT_CMD::CMD_TIN_L_TPD_HIDE_FRAME_TEMP	,	10},
        {PKT_CMD::CMD_TIN_L_ZOOM_CENTER_UP	,	10},
        {PKT_CMD::CMD_TIN_L_ZOOM_CENTER_DOWN	,	10},
        {PKT_CMD::CMD_TIN_L_ZOOM_POSITION_UP	,	10},
        {PKT_CMD::CMD_TIN_L_ZOOM_POSITION_DOWN	,	10},
        {PKT_CMD::CMD_TIN_L_DPC_ADD_DP	,	10},
        {PKT_CMD::CMD_TIN_L_DPC_REMOVE_DP	,	10},
        {PKT_CMD::CMD_TIN_L_DPC_AUTO_CALIBRATION	,	10},
        {PKT_CMD::CMD_TIN_L_PROP_LOAD_DEFAULT_PARAM	,	10},
        {PKT_CMD::CMD_TIN_L_PROP_AUTO_SHUTTER_PARAM_SET	,	10},
        {PKT_CMD::CMD_TIN_L_PROP_AUTO_SHUTTER_PARAM_GET	,	12},
        {PKT_CMD::CMD_TIN_L_PROP_IMAGE_PARAM_SET	,	10},
        {PKT_CMD::CMD_TIN_L_PROP_IMAGE_PARAM_GET	,	12},
        {PKT_CMD::CMD_TIN_L_PROP_OVER_EXPOSURE_SET	,	10},
        {PKT_CMD::CMD_TIN_L_PROP_OVER_EXPOSURE_GET	,	10},
        {PKT_CMD::CMD_TIN_L_PROP_TPD_PARAM_SET	,	10},
        {PKT_CMD::CMD_TIN_L_PROP_TPD_PARAM_GET	,	12},
        {PKT_CMD::CMD_TIN_END	,	10},
        {PKT_CMD::CMD_HI3217_START	,	10},
        {PKT_CMD::CMD_HI3217_END	,	10},
        {PKT_CMD::CMD_HI1612_START	,	10},
        {PKT_CMD::CMD_HI1612_END	,	10},
        {PKT_CMD::CMD_HI6417_START	,	10},
        {PKT_CMD::CMD_HI6417_END	,	10},
        {PKT_CMD::CMD_CFG_SET_DEFAULT	,	31},
        {PKT_CMD::CMD_CFG_READ_START	,	14},
        {PKT_CMD::CMD_CFG_READ_ING	,	39},
        {PKT_CMD::CMD_CFG_READ_END	,	10},
        {PKT_CMD::CMD_CFG_WRITE_START	,	10},
        {PKT_CMD::CMD_CFG_WRITE_ING	,	10},
        {PKT_CMD::CMD_CFG_WRITE_END	,	10},
        {PKT_CMD::CMD_CFG_SEC_SET_DEFAULT	,	26},
        {PKT_CMD::CMD_CFG_SEC_READ_START	,	14},
        {PKT_CMD::CMD_CFG_SEC_READ_ING	,	26},
        {PKT_CMD::CMD_CFG_SEC_READ_END	,	10},
        {PKT_CMD::CMD_CFG_SEC_WRITE_START	,	10},
        {PKT_CMD::CMD_CFG_SEC_WRITE_ING	,	10},
        {PKT_CMD::CMD_CFG_SEC_WRITE_END	,	10},
        {PKT_CMD::CMD_CFG_SEC_CHANGE_PW	,	10},
        {PKT_CMD::CMD_SYS_GET_VERSION	,	14},
        {PKT_CMD::CMD_SYS_GET_STATE	,	12},
        {PKT_CMD::CMD_SYS_GET_WHERE	,	10},
        {PKT_CMD::CMD_SYS_SET_WHERE	,	10},
        {PKT_CMD::CMD_SYS_GET_MODEL_NAME	,	26},
        {PKT_CMD::CMD_SYS_GET_PRODUCT_SN	,	26},
        {PKT_CMD::CMD_SYS_GET_UPTIME	,	14},
        {PKT_CMD::CMD_FLASH_START	,	10},
        {PKT_CMD::CMD_FLASH_ING	,	10},
        {PKT_CMD::CMD_FLASH_END	,	10},
        {PKT_CMD::CMD_NACK	,	10}
    };

    typedef enum PKT_RETURN : uint8_t
    {
        RET_OK = 0x00,
        RET_COMMAND_ERROR = 0x80,
        RET_UNKNOWN_COMMAND = 0x81,
        RET_WRONG_PACKET = 0x82,
        RET_INCORRECT_CHECKSUM = 0x83,
        RET_ZERO_PAYLOAD = 0x84,
        RET_INVALID_ARGUMENT = 0x85,
        RET_ERROR_OPERATION = 0x86
    };
    /// @endcond
}
